### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by mcrip2401** [januskh/Pixabay-Media-Search-and-Import-for-Umbraco#1]
After install the package and choose media area, the tab Pixabay shows a 404 error not finding "App_Plugins/Umbraco.Pixabay/views/browse.html"

**Comment by abjerner** [comment]
@januskh  It appears that the DLL file is missing in the Umbraco package, which is causing the error that @mcrip2401 is describing.

There is also a topic on Our Umbraco regarding the error: https://our.umbraco.org/forum/using-umbraco-and-getting-started/90708-pixabay-api

**Comment by januskh** [comment]
The DLL was apparrently not included in the package. So now there is a new version up.
