### ISSUE TITLE
Images not importing

### ISSUE THREAD

**Issue by OwainWilliams** [januskh/Pixabay-Media-Search-and-Import-for-Umbraco#2]
Hi, 
I've installed the package but when I click on import, I get the following errors:
`TypeError: Cannot read property 'length' of undefined`
and nothing is imported. 
Im using Umbraco 7.6.0

**Comment by JanusKampHansen** [comment]
Did you "check"/"select"/"flag" any images that you want to import?

**Comment by OwainWilliams** [comment]
Hi. 
Yip, I clicked on one image which put a green tick next to it. Then clicked import and nothing happened.

**Comment by JanusKampHansen** [comment]
I've been looking into the issue. Seems that all of a sudden Pixabay have changed their API. I will be looking into this ASAP. Stay tuned ;) (And thank you for reporting)

**Comment by januskh** [comment]
New bugfixed version available for download at Umbraco.
https://our.umbraco.org/projects/backoffice-extensions/pixabay-media-search-and-import-for-umbraco/
It been tested with Umbraco 7.6.0 too.

**Comment by OwainWilliams** [comment]
Great thanks! I've now installed the update and all works perfectly. Great package! #h5yr
